### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by HarukaYamamoto0** [KauaAmaroPires/Download_Youtube#1]
1. first I recommend writing the readme in English, so your package will have more reach.
2. you can use some useful packages like these to use in your package: [Inquirer.js](https://github.com/SBoudrias/Inquirer.js), [Chalk](https://github.com/chalk/chalk)
3. it would be nice to register your package as a global command.

at the moment I'm also creating a CLI but it's personal, you can learn how to create CLIs on this site: [medium](https://medium.com/henriquekuwai/criando-sua-cli-com-node-js-d6dee7d03110).
if you still haven't recognized me here i am the Splinta of zafriel's server

**Comment by KauaAmaroPires** [comment]
> 1. primeiro recomendo escrever o readme em inglês, assim seu pacote terá mais alcance.
> 2. você pode usar alguns pacotes úteis como estes para usar em seu pacote: [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) , [Chalk](https://github.com/chalk/chalk)
> 3. seria bom registrar seu pacote como um comando global.
> 
> no momento também estou criando uma CLI mas é pessoal, você pode aprender como criar CLIs neste site: [medium](https://medium.com/henriquekuwai/criando-sua-cli-com-node-js-d6dee7d03110) . se você ainda não me reconheceu aqui eu sou a Splinta do servidor do zafriel

Obrigado pelas dicas, eu vou dar uma olhada nesses pacotes e no site para melhorar o projeto.

**Comment by KauaAmaroPires** [comment]
> 1. first I recommend writing the readme in English, so your package will have more reach.
> 2. you can use some useful packages like these to use in your package: [Inquirer.js](https://github.com/SBoudrias/Inquirer.js), [Chalk](https://github.com/chalk/chalk)
> 3. it would be nice to register your package as a global command.
> 
> at the moment I'm also creating a CLI but it's personal, you can learn how to create CLIs on this site: [medium](https://medium.com/henriquekuwai/criando-sua-cli-com-node-js-d6dee7d03110). if you still haven't recognized me here i am the Splinta of zafriel's server

pronto, fiz as alterações, oq vc achou?

**Comment by HarukaYamamoto0** [comment]
achei bom, mais ainda dá para melhorar mais, como por exemplo melhorar mais o readme, para ficar mais atraente: [veja mais](https://blog.rocketseat.com.br/como-fazer-um-bom-readme/)

**Comment by HarukaYamamoto0** [comment]
vish sacanagem, eu tinha clonada o projeto aqui para o meu cell para eu poder fazer pull request de uma coisas que eu achava interessante, mais não vao dá pois na hora que eu tentei usar o `npm install` eu percebi que o puppeteer não é suportado na plataforma Android, sacanagem isso

**Comment by KauaAmaroPires** [comment]
> vish sacanagem, eu tinha clonada o projeto aqui para o meu cell para eu poder fazer pull request de uma coisas que eu achava interessante, mais não vao dá pois na hora que eu tentei usar o `npm install` eu percebi que o puppeteer não é suportado na plataforma Android, sacanagem isso

vish, eu n tinha testado no celular, só que eu já meio que previ isso, porque o puppeteer usa o chromium, ent provavelmente n iria funcionar msm

**Comment by HarukaYamamoto0** [comment]
é então eu acabo por aqui.

**Comment by KauaAmaroPires** [comment]
opa bom? eu fiz uma edit no projeto, agr ele pega no cell de boa

**Comment by HarukaYamamoto0** [comment]
[![asciicast](https://asciinema.org/a/586661.svg)](https://asciinema.org/a/586661)
