### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [KauaAmaroPires/Download_Youtube#4]
When running ytdlpl and downloading them as mp4s, they are saved in an unknown format that cannot be played.

**Comment by KauaAmaroPires** [comment]
Hello, thank you for reporting the error, I solved the problem, I discovered that there was some change in the YouTube API causing ytdl to stop working, I decided to use an alternative version to solve it.

**Comment by KauaAmaroPires** [comment]
> When running ytdlpl and downloading them as mp4s, they are saved in an unknown format that cannot be played.

Hello, thank you for reporting the error, I solved the problem, I discovered that there was some change in the YouTube API causing ytdl to stop working, I decided to use an alternative version to solve it.
